/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package commerce.training.car.garage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CarGarageProduct service. Represents a row in the &quot;CarGarageProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>commerce.training.car.garage.model.impl.CarGarageProductModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>commerce.training.car.garage.model.impl.CarGarageProductImpl</code>.
 * </p>
 *
 * @author Roselaine Marques
 * @see CarGarageProduct
 * @generated
 */
@ProviderType
public interface CarGarageProductModel
	extends BaseModel<CarGarageProduct>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a car garage product model instance should use the {@link CarGarageProduct} interface instead.
	 */

	/**
	 * Returns the primary key of this car garage product.
	 *
	 * @return the primary key of this car garage product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this car garage product.
	 *
	 * @param primaryKey the primary key of this car garage product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this car garage product.
	 *
	 * @return the uuid of this car garage product
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this car garage product.
	 *
	 * @param uuid the uuid of this car garage product
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the car garage product ID of this car garage product.
	 *
	 * @return the car garage product ID of this car garage product
	 */
	public long getCarGarageProductId();

	/**
	 * Sets the car garage product ID of this car garage product.
	 *
	 * @param carGarageProductId the car garage product ID of this car garage product
	 */
	public void setCarGarageProductId(long carGarageProductId);

	/**
	 * Returns the group ID of this car garage product.
	 *
	 * @return the group ID of this car garage product
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this car garage product.
	 *
	 * @param groupId the group ID of this car garage product
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this car garage product.
	 *
	 * @return the company ID of this car garage product
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this car garage product.
	 *
	 * @param companyId the company ID of this car garage product
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this car garage product.
	 *
	 * @return the user ID of this car garage product
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this car garage product.
	 *
	 * @param userId the user ID of this car garage product
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this car garage product.
	 *
	 * @return the user uuid of this car garage product
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this car garage product.
	 *
	 * @param userUuid the user uuid of this car garage product
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this car garage product.
	 *
	 * @return the user name of this car garage product
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this car garage product.
	 *
	 * @param userName the user name of this car garage product
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this car garage product.
	 *
	 * @return the create date of this car garage product
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this car garage product.
	 *
	 * @param createDate the create date of this car garage product
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this car garage product.
	 *
	 * @return the modified date of this car garage product
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this car garage product.
	 *
	 * @param modifiedDate the modified date of this car garage product
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the car garage ID of this car garage product.
	 *
	 * @return the car garage ID of this car garage product
	 */
	public long getCarGarageId();

	/**
	 * Sets the car garage ID of this car garage product.
	 *
	 * @param carGarageId the car garage ID of this car garage product
	 */
	public void setCarGarageId(long carGarageId);

	/**
	 * Returns the cp definition ID of this car garage product.
	 *
	 * @return the cp definition ID of this car garage product
	 */
	public long getCpDefinitionId();

	/**
	 * Sets the cp definition ID of this car garage product.
	 *
	 * @param cpDefinitionId the cp definition ID of this car garage product
	 */
	public void setCpDefinitionId(long cpDefinitionId);

	/**
	 * Returns the title of this car garage product.
	 *
	 * @return the title of this car garage product
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this car garage product.
	 *
	 * @param title the title of this car garage product
	 */
	public void setTitle(String title);

}