/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package commerce.training.car.garage.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import commerce.training.car.garage.model.CarGarageProduct;
import commerce.training.car.garage.model.CarGarageProductModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CarGarageProduct service. Represents a row in the &quot;CarGarageProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CarGarageProductModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CarGarageProductImpl}.
 * </p>
 *
 * @author Gavin Hinfey
 * @see CarGarageProductImpl
 * @generated
 */
@ProviderType
public class CarGarageProductModelImpl
	extends BaseModelImpl<CarGarageProduct> implements CarGarageProductModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a car garage product model instance should use the <code>CarGarageProduct</code> interface instead.
	 */
	public static final String TABLE_NAME = "CarGarageProduct";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"carGarageProductId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"carGarageId", Types.BIGINT}, {"cpDefinitionId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("carGarageProductId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("carGarageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cpDefinitionId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CarGarageProduct (uuid_ VARCHAR(75) null,carGarageProductId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,carGarageId LONG,cpDefinitionId LONG)";

	public static final String TABLE_SQL_DROP = "drop table CarGarageProduct";

	public static final String ORDER_BY_JPQL =
		" ORDER BY carGarageProduct.cpDefinitionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CarGarageProduct.cpDefinitionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		commerce.training.car.garage.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.commerce.training.car.garage.model.CarGarageProduct"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		commerce.training.car.garage.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.commerce.training.car.garage.model.CarGarageProduct"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		commerce.training.car.garage.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.commerce.training.car.garage.model.CarGarageProduct"),
		true);

	public static final long CARGARAGEID_COLUMN_BITMASK = 1L;

	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long CPDEFINITIONID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		commerce.training.car.garage.service.util.ServiceProps.get(
			"lock.expiration.time.commerce.training.car.garage.model.CarGarageProduct"));

	public CarGarageProductModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _carGarageProductId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCarGarageProductId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _carGarageProductId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CarGarageProduct.class;
	}

	@Override
	public String getModelClassName() {
		return CarGarageProduct.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CarGarageProduct, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CarGarageProduct, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarGarageProduct, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CarGarageProduct)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CarGarageProduct, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CarGarageProduct, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CarGarageProduct)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CarGarageProduct, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CarGarageProduct, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CarGarageProduct>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CarGarageProduct.class.getClassLoader(), CarGarageProduct.class,
			ModelWrapper.class);

		try {
			Constructor<CarGarageProduct> constructor =
				(Constructor<CarGarageProduct>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CarGarageProduct, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CarGarageProduct, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CarGarageProduct, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<CarGarageProduct, Object>>();
		Map<String, BiConsumer<CarGarageProduct, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CarGarageProduct, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object uuid) {

					carGarageProduct.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"carGarageProductId",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getCarGarageProductId();
				}

			});
		attributeSetterBiConsumers.put(
			"carGarageProductId",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct,
					Object carGarageProductId) {

					carGarageProduct.setCarGarageProductId(
						(Long)carGarageProductId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object groupId) {

					carGarageProduct.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object companyId) {

					carGarageProduct.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object userId) {

					carGarageProduct.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object userName) {

					carGarageProduct.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object createDate) {

					carGarageProduct.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object modifiedDate) {

					carGarageProduct.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"carGarageId",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getCarGarageId();
				}

			});
		attributeSetterBiConsumers.put(
			"carGarageId",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object carGarageId) {

					carGarageProduct.setCarGarageId((Long)carGarageId);
				}

			});
		attributeGetterFunctions.put(
			"cpDefinitionId",
			new Function<CarGarageProduct, Object>() {

				@Override
				public Object apply(CarGarageProduct carGarageProduct) {
					return carGarageProduct.getCpDefinitionId();
				}

			});
		attributeSetterBiConsumers.put(
			"cpDefinitionId",
			new BiConsumer<CarGarageProduct, Object>() {

				@Override
				public void accept(
					CarGarageProduct carGarageProduct, Object cpDefinitionId) {

					carGarageProduct.setCpDefinitionId((Long)cpDefinitionId);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCarGarageProductId() {
		return _carGarageProductId;
	}

	@Override
	public void setCarGarageProductId(long carGarageProductId) {
		_carGarageProductId = carGarageProductId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCarGarageId() {
		return _carGarageId;
	}

	@Override
	public void setCarGarageId(long carGarageId) {
		_columnBitmask |= CARGARAGEID_COLUMN_BITMASK;

		if (!_setOriginalCarGarageId) {
			_setOriginalCarGarageId = true;

			_originalCarGarageId = _carGarageId;
		}

		_carGarageId = carGarageId;
	}

	public long getOriginalCarGarageId() {
		return _originalCarGarageId;
	}

	@Override
	public long getCpDefinitionId() {
		return _cpDefinitionId;
	}

	@Override
	public void setCpDefinitionId(long cpDefinitionId) {
		_columnBitmask = -1L;

		_cpDefinitionId = cpDefinitionId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CarGarageProduct.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CarGarageProduct.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CarGarageProduct toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CarGarageProductImpl carGarageProductImpl = new CarGarageProductImpl();

		carGarageProductImpl.setUuid(getUuid());
		carGarageProductImpl.setCarGarageProductId(getCarGarageProductId());
		carGarageProductImpl.setGroupId(getGroupId());
		carGarageProductImpl.setCompanyId(getCompanyId());
		carGarageProductImpl.setUserId(getUserId());
		carGarageProductImpl.setUserName(getUserName());
		carGarageProductImpl.setCreateDate(getCreateDate());
		carGarageProductImpl.setModifiedDate(getModifiedDate());
		carGarageProductImpl.setCarGarageId(getCarGarageId());
		carGarageProductImpl.setCpDefinitionId(getCpDefinitionId());

		carGarageProductImpl.resetOriginalValues();

		return carGarageProductImpl;
	}

	@Override
	public int compareTo(CarGarageProduct carGarageProduct) {
		int value = 0;

		if (getCpDefinitionId() < carGarageProduct.getCpDefinitionId()) {
			value = -1;
		}
		else if (getCpDefinitionId() > carGarageProduct.getCpDefinitionId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CarGarageProduct)) {
			return false;
		}

		CarGarageProduct carGarageProduct = (CarGarageProduct)obj;

		long primaryKey = carGarageProduct.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CarGarageProductModelImpl carGarageProductModelImpl = this;

		carGarageProductModelImpl._originalUuid =
			carGarageProductModelImpl._uuid;

		carGarageProductModelImpl._originalGroupId =
			carGarageProductModelImpl._groupId;

		carGarageProductModelImpl._setOriginalGroupId = false;

		carGarageProductModelImpl._originalCompanyId =
			carGarageProductModelImpl._companyId;

		carGarageProductModelImpl._setOriginalCompanyId = false;

		carGarageProductModelImpl._setModifiedDate = false;

		carGarageProductModelImpl._originalCarGarageId =
			carGarageProductModelImpl._carGarageId;

		carGarageProductModelImpl._setOriginalCarGarageId = false;

		carGarageProductModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CarGarageProduct> toCacheModel() {
		CarGarageProductCacheModel carGarageProductCacheModel =
			new CarGarageProductCacheModel();

		carGarageProductCacheModel.uuid = getUuid();

		String uuid = carGarageProductCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			carGarageProductCacheModel.uuid = null;
		}

		carGarageProductCacheModel.carGarageProductId = getCarGarageProductId();

		carGarageProductCacheModel.groupId = getGroupId();

		carGarageProductCacheModel.companyId = getCompanyId();

		carGarageProductCacheModel.userId = getUserId();

		carGarageProductCacheModel.userName = getUserName();

		String userName = carGarageProductCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			carGarageProductCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			carGarageProductCacheModel.createDate = createDate.getTime();
		}
		else {
			carGarageProductCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			carGarageProductCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			carGarageProductCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		carGarageProductCacheModel.carGarageId = getCarGarageId();

		carGarageProductCacheModel.cpDefinitionId = getCpDefinitionId();

		return carGarageProductCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CarGarageProduct, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CarGarageProduct, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarGarageProduct, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CarGarageProduct)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CarGarageProduct, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CarGarageProduct, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarGarageProduct, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CarGarageProduct)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, CarGarageProduct>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _carGarageProductId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _carGarageId;
	private long _originalCarGarageId;
	private boolean _setOriginalCarGarageId;
	private long _cpDefinitionId;
	private long _columnBitmask;
	private CarGarageProduct _escapedModel;

}