/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package commerce.training.car.garage.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import commerce.training.car.garage.model.CarGarage;
import commerce.training.car.garage.model.CarGarageModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CarGarage service. Represents a row in the &quot;CarGarage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CarGarageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CarGarageImpl}.
 * </p>
 *
 * @author Roselaine Marques
 * @see CarGarageImpl
 * @generated
 */
public class CarGarageModelImpl
	extends BaseModelImpl<CarGarage> implements CarGarageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a car garage model instance should use the <code>CarGarage</code> interface instead.
	 */
	public static final String TABLE_NAME = "CarGarage";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"carGarageId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"cpDefinitionId", Types.BIGINT}, {"title", Types.VARCHAR},
		{"latitude", Types.DOUBLE}, {"longitude", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("carGarageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("cpDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CarGarage (uuid_ VARCHAR(75) null,carGarageId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,cpDefinitionId LONG,title VARCHAR(75) null,latitude DOUBLE,longitude DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table CarGarage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY carGarage.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CarGarage.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long CPDEFINITIONID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CarGarageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _carGarageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCarGarageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _carGarageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CarGarage.class;
	}

	@Override
	public String getModelClassName() {
		return CarGarage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CarGarage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CarGarage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarGarage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CarGarage)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CarGarage, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CarGarage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CarGarage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CarGarage, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CarGarage, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CarGarage>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CarGarage.class.getClassLoader(), CarGarage.class,
			ModelWrapper.class);

		try {
			Constructor<CarGarage> constructor =
				(Constructor<CarGarage>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CarGarage, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CarGarage, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CarGarage, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CarGarage, Object>>();
		Map<String, BiConsumer<CarGarage, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CarGarage, ?>>();

		attributeGetterFunctions.put("uuid", CarGarage::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<CarGarage, String>)CarGarage::setUuid);
		attributeGetterFunctions.put("carGarageId", CarGarage::getCarGarageId);
		attributeSetterBiConsumers.put(
			"carGarageId",
			(BiConsumer<CarGarage, Long>)CarGarage::setCarGarageId);
		attributeGetterFunctions.put("groupId", CarGarage::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<CarGarage, Long>)CarGarage::setGroupId);
		attributeGetterFunctions.put("companyId", CarGarage::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<CarGarage, Long>)CarGarage::setCompanyId);
		attributeGetterFunctions.put("userId", CarGarage::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<CarGarage, Long>)CarGarage::setUserId);
		attributeGetterFunctions.put("userName", CarGarage::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<CarGarage, String>)CarGarage::setUserName);
		attributeGetterFunctions.put("createDate", CarGarage::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CarGarage, Date>)CarGarage::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CarGarage::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CarGarage, Date>)CarGarage::setModifiedDate);
		attributeGetterFunctions.put(
			"cpDefinitionId", CarGarage::getCpDefinitionId);
		attributeSetterBiConsumers.put(
			"cpDefinitionId",
			(BiConsumer<CarGarage, Long>)CarGarage::setCpDefinitionId);
		attributeGetterFunctions.put("title", CarGarage::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<CarGarage, String>)CarGarage::setTitle);
		attributeGetterFunctions.put("latitude", CarGarage::getLatitude);
		attributeSetterBiConsumers.put(
			"latitude", (BiConsumer<CarGarage, Double>)CarGarage::setLatitude);
		attributeGetterFunctions.put("longitude", CarGarage::getLongitude);
		attributeSetterBiConsumers.put(
			"longitude",
			(BiConsumer<CarGarage, Double>)CarGarage::setLongitude);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCarGarageId() {
		return _carGarageId;
	}

	@Override
	public void setCarGarageId(long carGarageId) {
		_carGarageId = carGarageId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCpDefinitionId() {
		return _cpDefinitionId;
	}

	@Override
	public void setCpDefinitionId(long cpDefinitionId) {
		_columnBitmask |= CPDEFINITIONID_COLUMN_BITMASK;

		if (!_setOriginalCpDefinitionId) {
			_setOriginalCpDefinitionId = true;

			_originalCpDefinitionId = _cpDefinitionId;
		}

		_cpDefinitionId = cpDefinitionId;
	}

	public long getOriginalCpDefinitionId() {
		return _originalCpDefinitionId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		_latitude = latitude;
	}

	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		_longitude = longitude;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CarGarage.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CarGarage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CarGarage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CarGarage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CarGarageImpl carGarageImpl = new CarGarageImpl();

		carGarageImpl.setUuid(getUuid());
		carGarageImpl.setCarGarageId(getCarGarageId());
		carGarageImpl.setGroupId(getGroupId());
		carGarageImpl.setCompanyId(getCompanyId());
		carGarageImpl.setUserId(getUserId());
		carGarageImpl.setUserName(getUserName());
		carGarageImpl.setCreateDate(getCreateDate());
		carGarageImpl.setModifiedDate(getModifiedDate());
		carGarageImpl.setCpDefinitionId(getCpDefinitionId());
		carGarageImpl.setTitle(getTitle());
		carGarageImpl.setLatitude(getLatitude());
		carGarageImpl.setLongitude(getLongitude());

		carGarageImpl.resetOriginalValues();

		return carGarageImpl;
	}

	@Override
	public int compareTo(CarGarage carGarage) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), carGarage.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CarGarage)) {
			return false;
		}

		CarGarage carGarage = (CarGarage)obj;

		long primaryKey = carGarage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CarGarageModelImpl carGarageModelImpl = this;

		carGarageModelImpl._originalUuid = carGarageModelImpl._uuid;

		carGarageModelImpl._originalGroupId = carGarageModelImpl._groupId;

		carGarageModelImpl._setOriginalGroupId = false;

		carGarageModelImpl._originalCompanyId = carGarageModelImpl._companyId;

		carGarageModelImpl._setOriginalCompanyId = false;

		carGarageModelImpl._setModifiedDate = false;

		carGarageModelImpl._originalCpDefinitionId =
			carGarageModelImpl._cpDefinitionId;

		carGarageModelImpl._setOriginalCpDefinitionId = false;

		carGarageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CarGarage> toCacheModel() {
		CarGarageCacheModel carGarageCacheModel = new CarGarageCacheModel();

		carGarageCacheModel.uuid = getUuid();

		String uuid = carGarageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			carGarageCacheModel.uuid = null;
		}

		carGarageCacheModel.carGarageId = getCarGarageId();

		carGarageCacheModel.groupId = getGroupId();

		carGarageCacheModel.companyId = getCompanyId();

		carGarageCacheModel.userId = getUserId();

		carGarageCacheModel.userName = getUserName();

		String userName = carGarageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			carGarageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			carGarageCacheModel.createDate = createDate.getTime();
		}
		else {
			carGarageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			carGarageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			carGarageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		carGarageCacheModel.cpDefinitionId = getCpDefinitionId();

		carGarageCacheModel.title = getTitle();

		String title = carGarageCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			carGarageCacheModel.title = null;
		}

		carGarageCacheModel.latitude = getLatitude();

		carGarageCacheModel.longitude = getLongitude();

		return carGarageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CarGarage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CarGarage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarGarage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CarGarage)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CarGarage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CarGarage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CarGarage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CarGarage)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CarGarage>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _carGarageId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _cpDefinitionId;
	private long _originalCpDefinitionId;
	private boolean _setOriginalCpDefinitionId;
	private String _title;
	private double _latitude;
	private double _longitude;
	private long _columnBitmask;
	private CarGarage _escapedModel;

}